$(document).ready(function(){
    $('#cpp').click(function(){
      $('.cpp').fadeToggle();
    });
    $('#JS').click(function(){
        $('.js').fadeToggle();
    });
    $('#front').click(function(){
    $('.front').fadeToggle();    
    });
    $('#gmail').click(function(){
        $('p.gmail').fadeToggle();    
        });
    $('#whats').click(function(){
        $('p.whats').fadeToggle();    
        });
  });